Added no_mp3_support argument and added a check for ffmpg installation
CorentinJ/Real-Time-Voice-Cloning pull request #517
Opened 2020-09-01 23:11 UTC by ramalamadingdong

This is a fix for this [issue](https://github.com/CorentinJ/Real-Time-Voice-Cloning/issues/446) Please let me know if anything else needs to get done

2020-09-02 07:07 UTC, blue-fish commented
Hi @ramalamadingdong , thank you for contributing a fix for #446.

If we are going to distribute a sample mp3 with the repo, I'd prefer the reference audios from the [SV2TTS audio samples page](https://google.github.io/tacotron/publications/speaker_adaptation/index.html) since they can also be used for trying out the toolbox and benchmarking. We can get all 6 "speaker adaptation for unseen speakers" reference audios for 100k total: [**samples.zip**](https://github.com/CorentinJ/Real-Time-Voice-Cloning/files/5160607/samples.zip)

2020-09-02 14:14 UTC, blue-fish commented on demo_cli.py
> +                in_fpath = Path(input(message).replace("\"", "").replace("\'", ""))
```suggestion
                continue
```

2020-09-02 14:18 UTC, blue-fish commented on toolbox/__init__.py
> +                print("Error: No mp3 file argument was passed but an mp3 file was used")
```suggestion
                self.ui.log("Error: No mp3 file argument was passed but an mp3 file was used")
```

2020-09-02 14:20 UTC, blue-fish commented on toolbox/__init__.py
> +                exit(-1)
When this happens, let's do nothing instead of exiting
```suggestion
                return
```

2020-09-02 14:22 UTC, blue-fish commented on toolbox/__init__.py
> +        if (str(fpath)[-3:] == "mp3"):
```suggestion
        if fpath.suffix.lower() == ".mp3" and self.no_mp3_support:
```

2020-09-02 14:24 UTC, blue-fish commented on toolbox/__init__.py
> +                print("NoBackendError Exceptions raised please Install ffmpeg or rerun using no_mp3_support")
```suggestion
                print("Librosa will be unable to open mp3 files if additional software is not installed.\n"
                  "Please install ffmpeg or add the '--no_mp3_support' option to proceed without support for mp3 files.")
```

2020-09-02 14:31 UTC, blue-fish commented on toolbox/__init__.py
> +
```suggestion
            self.no_mp3_support = no_mp3_support
```

2020-09-02 18:24 UTC, ramalamadingdong commented on demo_cli.py
> +            if (str(in_fpath)[-3:] == "mp3"):
Thanks for this! I knew there must've been a better way to do it!

2020-09-03 02:42 UTC, ramalamadingdong commented
Did the updates and uploaded the correct samples :D

2020-09-03 07:24 UTC, blue-fish requested changes
In the future please make sure to test changes (the two that I found by testing escaped me during review).

1. Please add a file called `samples/README.md` with the following text. It is needed to comply with the requirements of the CC-BY-4.0 license.
````
The audio files in this folder are provided for toolbox testing and
benchmarking purposes. These are the same reference utterances
used by the SV2TTS authors to generate the audio samples located at:
https://google.github.io/tacotron/publications/speaker_adaptation/index.html

The `p240_00000.mp3` and `p260_00000.mp3` files are compressed
versions of audios from the VCTK corpus available at:
https://datashare.is.ed.ac.uk/handle/10283/3443
VCTK.txt contains the copyright notices and licensing information.

The `1320_00000.mp3`, `3575_00000.mp3`, `6829_00000.mp3`
and `8230_00000.mp3` files are compressed versions of audios
from the LibriSpeech dataset available at: https://openslr.org/12
For these files, the following notice applies:
```
LibriSpeech (c) 2014 by Vassil Panayotov

LibriSpeech ASR corpus is licensed under a
Creative Commons Attribution 4.0 International License.

See <http://creativecommons.org/licenses/by/4.0/>.
```
````
2. Please download README.txt from https://datashare.is.ed.ac.uk/handle/10283/3443 and import that to the repo as `samples/VCTK.txt`

2020-09-03 17:14 UTC, blue-fish approved these changes

2020-09-03 19:13 UTC, CorentinJ approved these changes

2020-09-03 22:31 UTC, merged