Update synthesizer/train.py, vocoder/train.py, synthesizer/synthesize.py, vocoder_preprocess.py to Allow Vocoder_preprocess to Work (Win10 GPU)
CorentinJ/Real-Time-Voice-Cloning pull request #838
Opened 2021-09-01 16:02 UTC by Tomcattwo

Pull requested by @blue-fish 
@tomcattwo edited synthesizer/train.py per issue #669 and blue-fish/Real-Time-Voice-Cloning@89a9964 to fix Win10 pickle issue.
This will allow Windows users using a GPU to properly run synthesizer training.

2021-09-01 16:47 UTC, Tomcattwo commented
Pulls requested by @blue-fish
1) In synthesizer/train.py @Tomcattwo edited per issue #669 and blue-fish/Real-Time-Voice-Cloning@89a9964 to fix Win10 pickle issue. This will allow Windows users using a GPU to properly run synthesizer training.
2) In vocoder/train.py @Tomcattwo edited per issue #669 and blue-fish/Real-Time-Voice-Cloning@89a9964 to fix Win10 pickle issue. This will allow Windows users using a GPU to properly run synthesizer training.
3) In synthesizer/synthesize.py, following edits made by @tomcattwo:
    a) added Win10 pickle fix per issue CorentinJ#669 and blue-fish/Real-Time-Voice-Cloning@89a9964 (lines 12 and 70)
    b) edited line 19 to delete "hparams" as argument; hparams_debug_string() needs 0 arguments. Allows vocoder_preprocess.py to run properly on WIn10/GPU (CUDA) systems)
    c) edited line 87 to fix improper definition for mels_out per @blue-fish recommendation in issue#729 and issue CorentinJ#833; Allows vocoder_preprocess.py to run properly on WIn10/GPU (CUDA) systems)
4) In vocoder_preorocess.py @Tomcattwo changed line 47 per recommendation by @blue-fish in issue CorentinJ#833; allows --cpu argument to be properly recognized

2021-09-08 15:37 UTC, blue-fish requested changes
Thank you for submitting the pull request @Tomcattwo .

Please remove all new comments. This information will be summarized in the commit message.

2021-09-08 15:37 UTC, blue-fish commented on synthesizer/synthesize.py
> +#@tomcattwo added below line to fix Win10 pickle error per issue #669 and  blue-fish/Real-Time-Voice-Cloning@89a9964
Please remove all new comments. This information will be summarized in the commit message.

2021-09-09 00:44 UTC, Tomcattwo commented
Additional comments removed. Please review.

2021-09-14 17:17 UTC, blue-fish approved these changes

2021-09-14 20:57 UTC, blue-fish commented
Resolves issues reported in #669 and #833. Also readme update to address #728.

2021-09-25 16:31 UTC, CorentinJ approved these changes

2021-09-25 16:57 UTC, merged

2021-09-25 16:57 UTC, blue-fish commented
Thank you for submitting the pull request @Tomcattwo .